type Query {
  client(id: ID!): Client
}

type Client {
  id: ID!
  name: String
  age: Int

  # вложенные поля
  documents: [Document]
  relatives: [Relative]
}

type Document {
  id: ID!
  type: String
  number: String
  issueDate: String
  expiryDate: String
}

type Relative {
  id: ID!
  relationType: String
  name: String
  age: Int
}

# Запросы

query {
  client(id: "123") {
    name
    age
  }
}

query {
  client(id: "123") {
    name
    documents {
      type
      number
    }
  }
}

query {
  client(id: "123") {
    relatives {
      name
      relationType
    }
  }
}

query GetClientData {
  client(id: "123") {
    name
    documents {
      type
      number
    }
    relatives {
      name
      relationType
    }
  }
}
